apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app-deployment
  labels:
    app: demo-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: demo-app
  template:
    metadata:
      labels:
        app: demo-app
    spec:
      containers:
      - name: demo-app
        image: monikarani1/php1:latest
        ports:
        - containerPort: 80
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 15
          timeoutSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: demo-app-service
spec:
  ports:
  - targetPort: 80
    port: 8080
    protocol: TCP
  selector:
    app: demo-app
  type: NodePort
